config/routes.rb
Rails.application.routes.draw do
  resources :microposttests
  resources :usertests
  resources :microposts
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/microposttest.rb
class Microposttest < ApplicationRecord
  #belongs_to :usertest
end

app/controllers/microposttests_controller.rb
class MicroposttestsController < ApplicationController
  before_action :set_microposttest, only: [:show, :edit, :update, :destroy]

  # GET /microposttests
  # GET /microposttests.json
  def index
    @microposttests = Microposttest.all
  end

  # GET /microposttests/1
  # GET /microposttests/1.json
  def show
  end

  # GET /microposttests/new
  def new
    @microposttest = Microposttest.new
  end

  # GET /microposttests/1/edit
  def edit
  end

  # POST /microposttests
  # POST /microposttests.json
  def create
    @microposttest = Microposttest.new(microposttest_params)

    respond_to do |format|
      if @microposttest.save
        format.html { redirect_to @microposttest, notice: 'Microposttest was successfully created.' }
        format.json { render :show, status: :created, location: @microposttest }
      else
        format.html { render :new }
        format.json { render json: @microposttest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposttests/1
  # PATCH/PUT /microposttests/1.json
  def update
    respond_to do |format|
      if @microposttest.update(microposttest_params)
        format.html { redirect_to @microposttest, notice: 'Microposttest was successfully updated.' }
        format.json { render :show, status: :ok, location: @microposttest }
      else
        format.html { render :edit }
        format.json { render json: @microposttest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposttests/1
  # DELETE /microposttests/1.json
  def destroy
    @microposttest.destroy
    respond_to do |format|
      format.html { redirect_to microposttests_url, notice: 'Microposttest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_microposttest
      @microposttest = Microposttest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def microposttest_params
      params.require(:microposttest).permit(:content, :user_id)
    end
end

app/helpers/microposttests_helper.rb
module MicroposttestsHelper
end

app/views/microposttests/_form.html.erb
<%= form_for(microposttest) do |f| %>
  <% if microposttest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(microposttest.errors.count, "error") %> prohibited this microposttest from being saved:</h2>

      <ul>
      <% microposttest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposttests/edit.html.erb
<h1>Editing Microposttest</h1>

<%= render 'form', microposttest: @microposttest %>

<%= link_to 'Show', @microposttest %> |
<%= link_to 'Back', microposttests_path %>

app/views/microposttests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposttests</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposttests.each do |microposttest| %>
      <tr>
        <td><%= microposttest.content %></td>
        <td><%= microposttest.user_id %></td>
        <td><%= link_to 'Show', microposttest %></td>
        <td><%= link_to 'Edit', edit_microposttest_path(microposttest) %></td>
        <td><%= link_to 'Destroy', microposttest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Microposttest', new_microposttest_path %>

app/views/microposttests/new.html.erb
<h1>New Microposttest</h1>

<%= render 'form', microposttest: @microposttest %>

<%= link_to 'Back', microposttests_path %>

app/views/microposttests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @microposttest.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @microposttest.user_id %>
</p>

<%= link_to 'Edit', edit_microposttest_path(@microposttest) %> |
<%= link_to 'Back', microposttests_path %>