config/routes.rb
Rails.application.routes.draw do
  resources :microposttests
  resources :usertests
  resources :microposts
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usertest.rb
class Usertest < ApplicationRecord
  has_many :microposttest
end

app/controllers/usertests_controller.rb
class UsertestsController < ApplicationController
  before_action :set_usertest, only: [:show, :edit, :update, :destroy]

  # GET /usertests
  # GET /usertests.json
  def index
    @usertests = Usertest.all
  end

  # GET /usertests/1
  # GET /usertests/1.json
  def show
  end

  # GET /usertests/new
  def new
    @usertest = Usertest.new
  end

  # GET /usertests/1/edit
  def edit
  end

  # POST /usertests
  # POST /usertests.json
  def create
    @usertest = Usertest.new(usertest_params)

    respond_to do |format|
      if @usertest.save
        format.html { redirect_to @usertest, notice: 'Usertest was successfully created.' }
        format.json { render :show, status: :created, location: @usertest }
      else
        format.html { render :new }
        format.json { render json: @usertest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usertests/1
  # PATCH/PUT /usertests/1.json
  def update
    respond_to do |format|
      if @usertest.update(usertest_params)
        format.html { redirect_to @usertest, notice: 'Usertest was successfully updated.' }
        format.json { render :show, status: :ok, location: @usertest }
      else
        format.html { render :edit }
        format.json { render json: @usertest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usertests/1
  # DELETE /usertests/1.json
  def destroy
    @usertest.destroy
    respond_to do |format|
      format.html { redirect_to usertests_url, notice: 'Usertest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usertest
      @usertest = Usertest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usertest_params
      params.require(:usertest).permit(:name, :email)
    end
end

app/helpers/usertests_helper.rb
module UsertestsHelper
end

app/views/usertests/_form.html.erb
<%= form_for(usertest) do |f| %>
  <% if usertest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usertest.errors.count, "error") %> prohibited this usertest from being saved:</h2>

      <ul>
      <% usertest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usertests/edit.html.erb
<h1>Editing Usertest</h1>

<%= render 'form', usertest: @usertest %>

<%= link_to 'Show', @usertest %> |
<%= link_to 'Back', usertests_path %>

app/views/usertests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usertests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usertests.each do |usertest| %>
      <tr>
        <td><%= usertest.name %></td>
        <td><%= usertest.email %></td>
        <td><%= link_to 'Show', usertest %></td>
        <td><%= link_to 'Edit', edit_usertest_path(usertest) %></td>
        <td><%= link_to 'Destroy', usertest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usertest', new_usertest_path %>

app/views/usertests/new.html.erb
<h1>New Usertest</h1>

<%= render 'form', usertest: @usertest %>

<%= link_to 'Back', usertests_path %>

app/views/usertests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @usertest.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usertest.email %>
</p>

<%= link_to 'Edit', edit_usertest_path(@usertest) %> |
<%= link_to 'Back', usertests_path %>